---
  - name: Configure domain integrations
    tasks:
  - name: Copy krb5
      copy:
      src: /var/lib/awx/projects/kerberos/krb5.conf
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: 0644

  - name: Copy smb.Conf
      copy:
      src: /var/lib/awx/projects/kerberos/smb.conf
      dest: /etc/samba/smb.conf
      owner: root
      group: root
      mode: 0644

  - name: Copy "/etc/sysconfig/squid"
      copy:
      src: /var/lib/awx/projects/kerberos/squid
      dest: /etc/sysconfig/
